### ISSUE TITLE
Donation / key assignment issue

### ISSUE THREAD

**Issue by 03gibbss** [SmartCasual/jingle-jam#103]
I added a new game to the existing bundle at set it to £10:

https://imgur.com/a/6dgIUo3

I created a second bundle and added only the witness to it:

https://imgur.com/a/BHlUYmR

I made a new donation of £60 (this account had already made donations to receive the bundle before). After the new donation there is a second key for The Witness (presumably from the new higher priced bundle), and no keys for the new game:

https://imgur.com/a/5XWzkqA

However, on the admin pages, the key for the new game has been assigned:

https://imgur.com/a/maIokPQ

Not entirely sure where this key has been assigned to. Maybe it is linked properly, just not showing correctly on the front end?

---

I added a few extra keys, made a fresh donation from an incognito window, and it assigned keys as intended:

https://imgur.com/a/V7ByM9L

---

Going back to my logged in window and making a new donation assigns a key for the new game:

https://imgur.com/a/GjrwRkx

---

Not sure this is an issue after all, I later made new games, added them to existing bundles, when a donation was made from another account it automatically assigned keys from the new games to all existing donators it seems.

**Comment by elliotcm** [comment]
Support for multiple bundle definitions is currently theoretical; I'd have to check what tests I have in place for that, but I had it largely pegged as a future nice-to-have since jingle jam is always one bundle.

That said, the job that assigns keys checks all bundles, and there's a couple of jobs intended to run frequently to check for unfulfilled bundles and rectify it.

That also said, it looks like I don't have that running on staging, and in fact I turned the resources down during our hiatus, so you could be looking at just aa lag time between you taking the actions and the free dynos spinning up the background workers.

Once I've got through the other bugs here I'll turn those back up to more production-like levels and you can have another go.

**Comment by elliotcm** [comment]
To be rechecked by @03gibbss  with proper staging resources near the end of the week.
