### ISSUE TITLE
Need to decide whether every donation over the bundle amount should receive a new bundle - maybe we add an 'opt out' button?

### ISSUE THREAD

**Issue by 03gibbss** [SmartCasual/jingle-jam#99]
Currently you only receive keys for your first donation, every subsequent donation over the minimum bundle amount won't give you an additional bundle.

- Maybe this is fine? If this is how we want it to work, then the wording needs to be very clear that you only receive the bundle once.

- Maybe the better option is to give the user a button to opt out of receiving a bundle, this allows them to receive multiple bundles if they want, but also gives them just the option to make a donation without receiving a bundle

- Donations on behalf of others is a to-do ticket which ties in with this

**Comment by 03gibbss** [comment]
Let's go with the 'opt-out' option. For every donation over the bundle amount there is a tick box with the option to opt-out of recieving a bundle, regardless of whether it's your 1st donation or your 50th.

Does the 'your keys' page have the ability to handle multiples of the same bundle? I'm thinking if someone buys the bundle 5 times it should have separate key pages for each version of the bundle.

**Comment by elliotcm** [comment]
The situation is quite a bit more complicated due to top up donations. I’m
not sure we can reasonably support both “top up mode” (multiple donations
can add together to contribute to you reaching the donation total / higher
tiers) and “opt out mode” at the same time.

Presenting the user with an opt out choice for “donations over the bundle
amount” requires knowledge about their past donations which we may not have
at that point (eg if they’ve not logged in yet).

If each donation is considered independent then that’s easier to do, but
otherwise it’s all a bit complex.

The app theoretically supports multiple of the same bundle for a single
person but in practice that’s untested.

We could potentially add a new post donation screen that asks what they
want to do?

As an edge case you’d still need to anticipate some support queries.

**Comment by elliotcm** [comment]
Pull request https://github.com/SmartCasual/jingle-jam/pull/152 implements my best idea on how to handle overpayments, and provides an option to choose which type of overpayment behaviour you want to use when creating a fundraiser.

It doesn't provide an "opt out" option in pro se mode but perhaps we can add that later.
